spring.application.name=tradingsimulationsystem


# --- Server Config ---
server.port=8080

# --- PostgreSQL Database Config ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tradingdb
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Config ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Logging (optional, for debugging SQL) ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
