# --- App Config ---
spring.application.name=tradingsimulationsystem
server.port=8080

# --- JWT Config ---
jwt.secret=mcewofmewimONOIEMoMOMoidmoiOoiIUMmlkMOKmomOIJWIJ93394039MDSDNE34NJFNERIJ
jwt.expiration=3600000

# --- PostgreSQL Database Config ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tradingdb
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Config ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Finnhub API Config ---
finnhub.api.key=d6sm8khr01qtlmfoh230d6sm8khr01qtlmfoh23g
finnhub.base.url=https://finnhub.io

# Market hours
market.open=09:00
market.close=15:30

# --- Logging ---
logging.level.org.springframework.web=DEBUG

# Enable seeding in dev/prod
app.seed-stocks=true
