# --- App Config ---
spring.application.name=tradingsimulationsystem
server.port=8080

# --- JWT Config ---
# Use a long plain string (?32 characters) for HS256
jwt.secret=neornfjNIONiuniNmoOmoiMOIJoijOKMomOImoiMKMKMD23J24839RJWEMWKMCKWNMCmkmjnwijniwncwwcdwce
# Token expiration in milliseconds (1 hour here)
jwt.expiration=3600000

# --- PostgreSQL Database Config ---
spring.datasource.url=jdbc:postgresql://localhost:5432/tradingdb
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Config ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Finnhub API Config ---
finnhub.api.key=d6s3j11r01qrb5i8fq3gd6s3j11r01qrb5i8fq40
finnhub.base.url=https://finnhub.io

# Market hours
market.open=09:00
market.close=15:30

# --- Logging (optional) ---
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

app.seed-stocks=true

